/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Jair Ramirez
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    int ContadorVidas;
    int rondas ;
    Random rand = new Random();
    String seleccion;
    int numero1;
    int numero2;        
    int numero3;
    int totalv;
    int resultado;
    public Juego() {
        initComponents();
        ContadorVidas=15;
        rondas = 0;
        vidasr.setText(Integer.toString(ContadorVidas));
        seleccion = "";
        totalv = 0;
        resultado =0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        text4 = new javax.swing.JTextField();
        num1 = new javax.swing.JLabel();
        Num2 = new javax.swing.JLabel();
        num3 = new javax.swing.JLabel();
        vidas = new javax.swing.JLabel();
        vidasr = new javax.swing.JTextField();
        operacion1 = new javax.swing.JComboBox<>();
        vSeleccion = new javax.swing.JComboBox<>();
        play = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        valorC = new javax.swing.JTextField();
        totalt = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        labelNumero = new javax.swing.JLabel();
        operacion2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("rondas");

        text1.setEditable(false);
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        text2.setEditable(false);

        text3.setEditable(false);

        text4.setEditable(false);
        text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text4ActionPerformed(evt);
            }
        });

        num1.setText("Numero 1");

        Num2.setText("Numero 2");

        num3.setText("Numero 3");

        vidas.setText("Vidas restantes");

        vidasr.setEditable(false);
        vidasr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidasrActionPerformed(evt);
            }
        });

        operacion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "x", "÷" }));
        operacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacion1ActionPerformed(evt);
            }
        });

        vSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numero 1 y Numero 2", "Numero 1 y Numero 3", "Numero 2 y Numero 3" }));
        vSeleccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vSeleccionItemStateChanged(evt);
            }
        });
        vSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vSeleccionActionPerformed(evt);
            }
        });

        play.setText("Jugar");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        valorC.setEditable(false);

        totalt.setText("Resultado");

        calcular.setText("total");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        labelNumero.setText("Numero 3");

        operacion2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "x", "÷" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(num1)
                    .addComponent(Num2)
                    .addComponent(num3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text4)
                    .addComponent(text2)
                    .addComponent(text3)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(play)
                        .addGap(18, 18, 18)
                        .addComponent(reset))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(calcular))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(vSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(vidas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(vidasr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(totalt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(valorC, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(operacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(operacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidas)
                    .addComponent(vidasr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Num2)
                        .addComponent(operacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(operacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3)
                    .addComponent(valorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalt)
                    .addComponent(calcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(play)
                    .addComponent(reset))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text4ActionPerformed

    private void vidasrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidasrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vidasrActionPerformed

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_text1ActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        if (ContadorVidas>0){
        text1.setText(Integer.toString(rondas+1));
        rondas= rondas+1;
        vidasr.setText(Integer.toString(ContadorVidas));
        int d1 =rand.nextInt(5)+1;
        numero1=d1;
        int d2 =rand.nextInt(5)+1;
        numero2=d2;
        int d3 =rand.nextInt(5)+1;
        numero3=d3;
        text2.setText(Integer.toString(d1));
        text3.setText(Integer.toString(d2));
        text4.setText(Integer.toString(d3));  
        }
        else {
        JOptionPane.showMessageDialog(null,"Usted ya no tiene Vidas"+"\nNumero de Rondas: "+rondas);
        }
    }//GEN-LAST:event_playActionPerformed

    private void vSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vSeleccionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_vSeleccionActionPerformed

    private void vSeleccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vSeleccionItemStateChanged
        // TODO add your handling code here:
        seleccion = (String)vSeleccion.getSelectedItem();
        if (seleccion.equals("Numero 1 y Numero 2") ){
            labelNumero.setText("Numero 3");
        }
        if (seleccion.equals("Numero 1 y Numero 3") ){
            labelNumero.setText("Numero 2");
        }
        if (seleccion.equals("Numero 2 y Numero 3") ){
            labelNumero.setText("Numero 1");
        }
    }//GEN-LAST:event_vSeleccionItemStateChanged

    private void operacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operacion1ActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        if (seleccion.equals("Numero 1 y Numero 2")==true && operacion1.equals("+")==true){
        resultado = numero1+numero2;
            System.out.println(resultado);
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        }
        if (seleccion.equals("Numero 1 y Numero 3") && operacion1.equals("+")==true){
        resultado = numero1+numero3;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        }
        if (seleccion.equals("Numero 2 y Numero 3") && operacion1.equals("+")==true){
        resultado = numero2-numero3;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        }
        
        if (seleccion.equals("Numero 1 y Numero 2") && operacion1.equals("-")==true){
        resultado = numero1-numero2;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        }
        if (seleccion.equals("Numero 1 y Numero 3") && operacion1.equals("-")==true){
        resultado = numero1-numero3;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        
        }
        if (seleccion.equals("Numero 2 y Numero 3") && operacion1.equals("-")==true){
        resultado = numero2-numero3;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        
        }  
       
        if (seleccion.equals("Numero 1 y Numero 2") && operacion1.equals("x")==true){
        resultado = numero1*numero2;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        
        }
        if (seleccion.equals("Numero 1 y Numero 3") && operacion1.equals("x")==true){
        resultado = numero1*numero3;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        }
        if (seleccion.equals("Numero 2 y Numero 3") && operacion1.equals("x")==true){
        resultado = numero2*numero3;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        }
        
        if (seleccion.equals("Numero 1 y Numero 2") && operacion1.equals("÷")==true){
        resultado = numero1/numero2;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        }
        if (seleccion.equals("Numero 1 y Numero 3") && operacion1.equals("÷")==true){
        resultado = numero1/numero3;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;
        }
        }
        if (seleccion.equals("Numero 2 y Numero 3") && operacion1.equals("÷")==true){
        resultado = numero2/numero3;
        if(operacion2.equals("+")==true){
        totalv = resultado + numero3;
        }
        if(operacion2.equals("-")==true){
        totalv = resultado - numero3;
        }
        if(operacion2.equals("x")==true){
        totalv = resultado * numero3;
        }
        if(operacion2.equals("÷")==true){
        totalv = resultado / numero3;        
        }
        }
        valorC.setText(Integer.toString(totalv));

        
  
    }//GEN-LAST:event_calcularActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Num2;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num3;
    private javax.swing.JComboBox<String> operacion1;
    private javax.swing.JComboBox<String> operacion2;
    private javax.swing.JButton play;
    private javax.swing.JButton reset;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JLabel totalt;
    private javax.swing.JComboBox<String> vSeleccion;
    private javax.swing.JTextField valorC;
    private javax.swing.JLabel vidas;
    private javax.swing.JTextField vidasr;
    // End of variables declaration//GEN-END:variables
}
